LEXICON_RU = {
    '/help': 'Это ответ на команду /help',
    '/start': 'Добро пожаловать!',
    'total_customers_this_week': 'Всего клиентов на этой неделе:',
    'want_see_customers': 'Хотите увидеть список клиентов?',
    'yes': 'Да',
    'no': 'Нет',
    'customers_list': 'Список клиентов:',
    'no_customers_found': 'Клиентов не найдено на этой неделе.',
    'this_is_not_your_query': 'Это не ваша команда',
    'error_processing_image': 'Ошибка при обработке изображения:',
    'similar_image_found': 'Найдено похожее изображение от пользователя',
    'uploaded_on': 'загружено',
    'timestamp': 'временная метка',
    'location': 'местоположение',
    'starting_db_population': 'Начинаю заполнение базы данных изображениями...',
    'db_population_completed': 'Заполнение базы данных завершено. Затрачено времени:',
    'seconds': 'секунд',
    'send_excel_route': '📊 Отправьте Excel файл (.xlsx) с данными маршрутов.\n\n',
    'send_excel_equip': '📊 Отправьте Excel файл (.xlsx) с данными оборудования/клиентов.\n\n',
}

LEXICON_UZ = {
    '/help': 'Bu /help komandasi uchun javob',
    '/start': 'Xush kelibsiz!',
    'total_customers_this_week': 'Shu haftada jami mijozlar:',
    'want_see_customers': 'Mijozlar ro\'yxatini ko\'rishni xohlaysizmi?',
    'yes': 'Ha',
    'no': 'Yo\'q',
    'customers_list': 'Mijozlar ro\'yxati:',
    'no_customers_found': 'Shu haftada mijozlar topilmadi.',
    'this_is_not_your_query': 'Bu sizning komandasingiz emas',
    'error_processing_image': 'Rasm qayta ishlashda xato:',
    'similar_image_found': 'Foydalanuvchi tomon o\'xshash rasm topildi',
    'uploaded_on': 'yuklandi',
    'timestamp': 'vaqt belgisi',
    'location': 'joylashuv',
    'starting_db_population': 'Ma\'lumotlar bazasini rasmlar bilan to\'ldirish boshlanmoqda...',
    'db_population_completed': 'Ma\'lumotlar bazasi to\'ldirish tugallandi. Sarflangan vaqt:',
    'seconds': 'soniya',
    'send_excel_route': '📊 Marshrut ma\'lumotlari bilan Excel fayli (.xlsx) yuboring.\n\n',
    'send_excel_equip': '📊 Mijozdagi stoykalar to\'g\'risidagi ma\'lumotlari bilan Excel fayli (.xlsx) yuboring.\n\n',
}